version: '3'

services:
  #Деплой nginx
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "8687:80"
    depends_on:
      - backend_project
    restart: always
    networks:
      - internal

  #Деплой Postgres
  db:
    image: postgres:12.0-alpine
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    restart: always
    networks:
      - internal

  backend_project_migrations:
    build:
      context: ./backend_project
      dockerfile: Dockerfile
    command: python manage.py migrate
    volumes:
      - ./backend_project:/code  # Монтируем папку backend_project в /code в контейнере
    networks:
      - internal
    depends_on:
      - db
    env_file:
      - ./.env.dev

  #Деплой сервера Django
  backend_project:
    build:
      context: ./backend_project  # Относительный путь к папке backend_project
      dockerfile: Dockerfile
    command: gunicorn --config gunicorn.conf.py backend_project.wsgi:application
    expose:
      - "8000:8000"
    volumes:
      - ./backend_project:/code  # Монтируем папку backend_project в /code в контейнере
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    networks:
      - internal
    restart: always
    depends_on:
      - rabbitmq
      - minio
      - db
      - backend_project_migrations
    env_file:
      - ./.env.dev

  #Деплой RabbitMQ
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"  # Для AMQP
      - "15672:15672"  # Для веб-интерфейса управления
    networks:
      - internal
    env_file:
      - ./.env.dev.rbmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3


  # Деплой MinIO
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    networks:
      - internal
    restart: always
    env_file:
      - ./.env.dev.minio


networks:
  internal:
    driver: bridge

volumes:
  minio_data:
    driver: local
  static_volume:
  media_volume:
  postgres_data: