# Generated by Django 5.0.2 on 2024-04-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_diagnosisrequest_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingservice',
            name='description',
            field=models.CharField(default='Without description :(', max_length=500),
        ),
        migrations.AlterField(
            model_name='processingservice',
            name='health_check_url',
            field=models.URLField(null=True),
        ),
    ]
