# Generated by Django 5.0.2 on 2024-04-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_processingservice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='complaints',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='full_path',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.patient'),
        ),
    ]
