# Generated by Django 5.0.2 on 2024-05-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_diagnosisrequest_complaints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_diagnosis_request', to='api.diagnosisrequest')),
            ],
        ),
    ]
