# Generated by Django 5.0.2 on 2024-05-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_diagnosis_request', to='api.diagnosisrequest'),
        ),
    ]
