# Generated by Django 5.0.2 on 2024-05-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_feedback_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingservice',
            name='short_name',
            field=models.TextField(null=True),
        ),
    ]
